#!/usr/bin/env python3
"""
Pytest‑style integration test for the cheese fungus segmentation pipeline.

It:
    1. Calls ``segment_cheese_fungus_integration.py`` on the synthetic data
       (generated by ``generate_test_data.py``).
    2. Verifies that all three output artefacts are created and contain data.
    3. Checks that the CSV summary contains numeric values ≥ 0.
"""

import subprocess
import pathlib
import csv

def test_integration():
    # ------------------------------------------------------------------
    # 1️⃣ Run the processing script on the synthetic data
    # ------------------------------------------------------------------
    cmd = [
        "python",
        "segment_cheese_fungus_integration.py",
        "--hsi_path", "test_cube.npy",
        "--csv_path", "test_fungus_ref.csv",
        "--output_dir", "integration_test_output",
        "--thresh", "0.12",
        "--mnf_components", "5",
        "--min_mask_area", "5",
        "--margin", "2"
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    # The script must exit cleanly (return code 0)
    assert result.returncode == 0, f"Processing script failed: {result.stderr}"

    # ------------------------------------------------------------------
    # 2️⃣ Verify that the three expected artefacts exist and are non‑empty
    # ------------------------------------------------------------------
    out_dir = pathlib.Path("integration_test_output")
    for fname in ["test_cube_mask.tif", "test_cube_overlay.png", "test_cube_summary.csv"]:
        path = out_dir / fname
        assert path.exists(), f"Expected file {fname} not found"
        assert path.stat().st_size > 0, f"File {fname} is empty"

    # ------------------------------------------------------------------
    # 3️⃣ Sanity‑check the CSV summary contains numeric values
    # ------------------------------------------------------------------
    csv_path = out_dir / "test_cube_summary.csv"
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        row = next(reader)
        for key in ["total_pixels", "fungus_pixels", "percentage_fungus"]:
            assert key in row, f"CSV missing column {key}"
            assert float(row[key]) >= 0, f"Column {key} contains negative value {row[key]}"

    print("✅ All integration‑test checks passed!")


if __name__ == "__main__":
    test_integration()